In [2]:
import numpy as np
import pandas as pd

In [ ]:
# Matriz de confusão normalizada
conf_matrix_norm = np.array([
    [1.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00],  # Classe 0
    [0.00, 0.99, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00],   # Classe 1
    [0.00, 0.00, 0.98, 0.01, 0.00, 0.00, 0.00, 0.01, 0.00, 0.00],   # Classe 2
    [0.00, 0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00],   # Classe 3
    [0.00, 0.00, 0.00, 0.00, 0.99, 0.00, 0.00, 0.00, 0.00, 0.01],   # Classe 4
    [0.00, 0.00, 0.00, 0.02, 0.00, 0.98, 0.00, 0.00, 0.00, 0.00],   # Classe 5
    [0.01, 0.00, 0.00, 0.00, 0.00, 0.00, 0.99, 0.00, 0.00, 0.00],   # Classe 6
    [0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 1.00, 0.00, 0.00],   # Classe 7
    [0.00, 0.00, 0.00, 0.01, 0.00, 0.00, 0.00, 0.00, 0.99, 0.00],   # Classe 8
    [0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.01, 0.00, 0.98]    # Classe 9
])

# Converter para matriz de contagem absoluta
conf_matrix = (conf_matrix_norm * 100).astype(int)

In [4]:
# Função para calcular todas as métricas
def calcular_metricas(matriz_confusao):
    metricas = []
    num_classes = matriz_confusao.shape[0]
    
    for i in range(num_classes):
        VP = matriz_confusao[i,i]
        FN = np.sum(matriz_confusao[i,:]) - VP
        FP = np.sum(matriz_confusao[:,i]) - VP
        VN = np.sum(matriz_confusao) - (VP + FP + FN)
        
        # Cálculo das métricas
        acuracia = (VP + VN) / (VP + FP + FN + VN)
        sensibilidade = VP / (VP + FN) if (VP + FN) > 0 else 0
        especificidade = VN / (VN + FP) if (VN + FP) > 0 else 0
        precisao = VP / (VP + FP) if (VP + FP) > 0 else 0
        f1_score = 2 * (precisao * sensibilidade) / (precisao + sensibilidade) if (precisao + sensibilidade) > 0 else 0
        
        metricas.append({
            'Classe': i,
            'VP': VP,
            'FN': FN,
            'FP': FP,
            'VN': VN,
            'Acurácia': acuracia,
            'Sensibilidade (Recall)': sensibilidade,
            'Especificidade': especificidade,
            'Precisão': precisao,
            'F1-Score': f1_score
        })
    
    return metricas


In [5]:
# Calcular métricas para todas as classes
metricas_classes = calcular_metricas(conf_matrix)

# Criar DataFrame para exibição
df_metricas = pd.DataFrame(metricas_classes)

# Calcular médias
medias = {
    'Métrica': ['Média'],
    'Acurácia': [df_metricas['Acurácia'].mean()],
    'Sensibilidade (Recall)': [df_metricas['Sensibilidade (Recall)'].mean()],
    'Especificidade': [df_metricas['Especificidade'].mean()],
    'Precisão': [df_metricas['Precisão'].mean()],
    'F1-Score': [df_metricas['F1-Score'].mean()]
}

In [6]:
# Exibir resultados
print("Matriz de Confusão (valores absolutos):")
print(conf_matrix)
print("\nMétricas por Classe:")
print(df_metricas.to_string(index=False))
print("\nMédias Gerais:")
print(pd.DataFrame(medias).to_string(index=False))

Matriz de Confusão (valores absolutos):
[[100   0   0   0   0   0   0   0   0   0]
 [  0  99   0   0   0   0   0   0   0   0]
 [  0   0  98   1   0   0   0   1   0   0]
 [  0   0   0 100   0   0   0   0   0   0]
 [  0   0   0   0  99   0   0   0   0   1]
 [  0   0   0   2   0  98   0   0   0   0]
 [  1   0   0   0   0   0  99   0   0   0]
 [  0   0   0   0   0   0   0 100   0   0]
 [  0   0   0   1   0   0   0   0  99   0]
 [  0   0   0   0   0   0   0   1   0  98]]

Métricas por Classe:
 Classe  VP  FN  FP  VN  Acurácia  Sensibilidade (Recall)  Especificidade  Precisão  F1-Score
      0 100   0   1 897  0.998998                1.000000        0.998886  0.990099  0.995025
      1  99   0   0 899  1.000000                1.000000        1.000000  1.000000  1.000000
      2  98   2   0 898  0.997996                0.980000        1.000000  1.000000  0.989899
      3 100   0   4 894  0.995992                1.000000        0.995546  0.961538  0.980392
      4  99   1   0 898  0.998998    